spring.application.name=journalApp
spring.data.mongodb.uri=mongodb+srv://lokeshjmy_db_user:OKQxcUzMFsqdnfwA@cluster0.cffdj8e.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true